version: "3.8"
services:
  backend:
    build: ./backend
    image: backend:latest
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    image: frontend:latest
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always
